# NumPy 기본

* Numerical Python
* 산술 계산을 위한 가장 중요한 필수 패키지



### Numpy의 기능

* 다차원 배열인 **ndarray** 
  * 빠른 배열 계산
* 반복문 없이 전체 데이터 배열을 빠르게 계산
* 배열 데이터를 디스크에 쓰거나 읽을 수 있음
* 선형대수, 난수 생성기, 푸리에 변환기능
* C로 작성한 코드를 연결할 수 있는 C API 제공

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

### 배열(ndarray) vs 리스트

* 곱셈 연산 처리속도 비교

In [8]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [9]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 27.7 ms
Wall time: 1.6 s


Numpy를 사용한 코드가 리스트보다 10~100배 이상 빠름

##  NumPy ndarray

In [15]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.0929,  0.2817,  0.769 ],
       [ 1.2464,  1.0072, -1.2962]])

In [16]:
# 산술연산(곱셈)
data * 10

array([[  0.9291,   2.8175,   7.6902],
       [ 12.4643,  10.0719, -12.9622]])

In [17]:
# 산술연산(덧셈)
data + data

array([[ 0.1858,  0.5635,  1.538 ],
       [ 2.4929,  2.0144, -2.5924]])

In [18]:
# 배열의 차원을 튜플 형태로 반환
data.shape

(2, 3)

In [20]:
# 배열에 저장된 자료형
data.dtype

dtype('float64')

### ndarrays 생성하기

* 리스트로 만들기
* 0으로 채우기
* 가비지 값으로 채우기

-----
* ndim 
* shape
* dtype
* empty

In [21]:
# 리스트를 ndarray로 변환
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
# 리스트를 ndarray(다차원 배열)로 변환
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [30]:
# 0으로 초기화된 배열
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
# 0으로 초기화된 배열
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
# 가비지값으로 채워진 배열
np.empty((2, 3, 2))

array([[[1.2351e-311, 2.8162e-322],
        [0.0000e+000, 0.0000e+000],
        [0.0000e+000, 1.3137e-076]],

       [[7.4864e-091, 9.7684e+165],
        [5.4509e-067, 7.1929e-067],
        [6.4822e+170, 4.9343e+257]]])

In [35]:
# range 함수와 유사, array에서는 arange를 사용
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray의 dtype

* dtype
* astype

In [37]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [42]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

### NumPy 배열의 산술연산

* 같은 크기의 배열간의 산술 연산은 배열의 각 원소 단위로 적용된다

In [55]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [57]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [59]:
arr ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

In [60]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [61]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 인덱싱과 슬라이싱 기초

#### 1차원배열

In [62]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[5]

5

In [64]:
arr[5:8]

array([5, 6, 7])

In [65]:
arr[5:8] = 12

In [66]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [67]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [68]:
#arr_slice값을 변경하면, arr값도 변경됨
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [70]:
# [:] : 배열의 모든값이 변경
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

#### 다차원배열

In [71]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [72]:
arr2d[0][2]

3

In [73]:
arr2d[0, 2]

3

In [74]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[1, 0]

array([7, 8, 9])

### 불리언 색인: 불리언값으로 선택하기

In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [89]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [90]:
data

array([[-2.3594, -0.1995, -1.542 , -0.9707],
       [-1.307 ,  0.2863,  0.378 , -0.7539],
       [ 0.3313,  1.3497,  0.0699,  0.2467],
       [-0.0119,  1.0048,  1.3272, -0.9193],
       [-1.5491,  0.0222,  0.7584, -0.6605],
       [ 0.8626, -0.01  ,  0.05  ,  0.6702],
       [ 0.853 , -0.9559, -0.0235, -2.3042]])

In [91]:
#불리언 배열을 반환
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [92]:
# 불리언 배열을 배열의 색인으로 사용
data[names == 'Bob']

array([[-2.3594, -0.1995, -1.542 , -0.9707],
       [-0.0119,  1.0048,  1.3272, -0.9193]])

In [97]:
data[data < 0] = 0
data

array([[0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.2863, 0.378 , 0.    ],
       [0.3313, 1.3497, 0.0699, 0.2467],
       [0.    , 1.0048, 1.3272, 0.    ],
       [0.    , 0.0222, 0.7584, 0.    ],
       [0.8626, 0.    , 0.05  , 0.6702],
       [0.853 , 0.    , 0.    , 0.    ]])

In [98]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [0.    , 0.2863, 0.378 , 0.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.8626, 0.    , 0.05  , 0.6702],
       [0.853 , 0.    , 0.    , 0.    ]])

### 팬시 색인

In [99]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [100]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [101]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

### 배열 전치와 축 바꾸기

In [106]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [107]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [108]:
arr = np.random.randn(6, 3)
arr

array([[-0.6525, -1.2183, -1.3326],
       [ 1.0746,  0.7236,  0.69  ],
       [ 1.0015, -0.5031, -0.6223],
       [-0.9212, -0.7262,  0.2229],
       [ 0.0513, -1.1577,  0.8167],
       [ 0.4336,  1.0107,  1.8249]])

In [110]:
# 행렬의 내적 연산: np.dot
np.dot(arr.T, arr)

array([[3.6228, 2.1165, 1.6156],
       [2.1165, 5.1503, 3.173 ],
       [1.6156, 3.173 , 6.686 ]])

In [111]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## 유니버셜 함수: 배열의 각 원소를 빠르게 처리

In [115]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.sqrt(arr)

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [117]:
np.exp(arr)

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [118]:
x = np.random.randn(8)
y = np.random.randn(8)

In [119]:
x

array([-0.9975,  0.8506, -0.1316,  0.9124,  0.1882,  2.1695, -0.1149,
        2.0037])

In [120]:
y

array([ 0.0296,  0.7953,  0.1181, -0.7485,  0.585 ,  0.1527, -1.5657,
       -0.5625])

In [121]:
np.maximum(x, y)

array([ 0.0296,  0.8506,  0.1181,  0.9124,  0.585 ,  2.1695, -0.1149,
        2.0037])

## 배열을 이용한 배열지향 프로그래밍

### 수학/통계 메소드

In [175]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [176]:
arr.mean()

4.5

In [177]:
np.mean(arr)

4.5

In [178]:
arr.sum()

36

In [179]:
arr.mean(axis=1)

array([2.5, 6.5])

In [180]:
arr.sum(axis=0)

array([ 6,  8, 10, 12])

In [181]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [184]:
# 각 원소의 누적합
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [185]:
# 각 원소의 누적곱
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### 불리언 배열을 위한 메서드

In [192]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

53

In [193]:
bools = np.array([False, False, True, False])
#하나 이상의 값이 True인지 검사
bools.any()

True

In [194]:
#하나 이상의 값이 False인지 검사
bools.all()

False

### 정렬

In [196]:
arr = np.random.randn(6)
arr

array([-0.9406,  1.0021, -0.5254, -0.8874,  1.8313, -0.923 ])

In [197]:
arr.sort()
arr

array([-0.9406, -0.923 , -0.8874, -0.5254,  1.0021,  1.8313])

In [198]:
arr = np.random.randn(5, 3)
arr

array([[ 0.7005, -0.8922,  2.3007],
       [-0.8178,  0.5138,  0.6236],
       [ 1.4892,  1.9405,  0.5432],
       [ 0.5062,  1.662 , -1.1892],
       [ 0.0936, -0.5392, -1.4374]])

In [200]:
# 1차원 부분 정렬
arr.sort(1)
arr

array([[-0.8922,  0.7005,  2.3007],
       [-0.8178,  0.5138,  0.6236],
       [ 0.5432,  1.4892,  1.9405],
       [-1.1892,  0.5062,  1.662 ],
       [-1.4374, -0.5392,  0.0936]])

In [202]:
large_arr = np.random.randn(1000)
large_arr.sort()

#5% 분위수
large_arr[int(0.05 * len(large_arr))]

-1.6777648710198625

## 난수 생성

In [204]:
# 표준정규분포를 따르는 4x4 표본 생성
samples = np.random.normal(size=(4,4))
samples

array([[-1.3823, -1.3511,  0.2584,  0.0635],
       [-0.087 ,  0.5993, -1.2208,  0.014 ],
       [-0.0229, -0.8245, -0.3303, -0.9927],
       [-1.2172,  0.2175,  0.4409,  0.3353]])

In [213]:
# np.random.seed(1)
val = np.random.randn()
val

-0.5281717522634557