In [112]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [113]:
redwine = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";", header=0)
redwine["type"] = "red"
whitewine = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=";", header=0)
whitewine["type"] = "white"
wine = redwine.append(whitewine)

In [114]:
redwine.shape
redwine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality type  
0         9.4        5  red  
1         9.8        5  red  
2         9.8        5  red  
3         9.8        6  red  
4         9.4        5  red  
...       ...      ...  ...  
1594     10.5        5  red  
1595     11.2        6  red  
1596     11.0        6  red  
1597     10.2        5  red  
1598     11.0        6  red  

[1599 rows x 13 columns]

In [115]:
wine.shape

(6497, 13)

In [116]:
X = wine.drop(["type", "quality"], axis=1)
X.shape

(6497, 11)

In [117]:
y = wine.quality
print(y)
print(y.shape)

0       5
1       5
2       5
3       6
4       5
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 6497, dtype: int64
(6497,)


In [118]:
regr = LinearRegression()

In [119]:
regr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [121]:
r = regr.predict(X)
result =  np.round(r) - y

plt.plot(result, '*')

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6497 and the array at index 1 has size 1

In [90]:
 np.sum(   np.abs(np.round(r) - y)  <= 1) / y.size

0.9495151608434662

In [91]:
print(regr.coef_)

[ 6.76839156e-02 -1.32789221e+00 -1.09656648e-01  4.35587507e-02
 -4.83713531e-01  5.96988830e-03 -2.48129841e-03 -5.49669422e+01
  4.39296072e-01  7.68251760e-01  2.67030009e-01]


In [92]:
plt.plot(regr.coef_)

TypeError: plot() missing 1 required positional argument: 'ys'

In [93]:
x = np.array([7.4, 0.5, 0.2, 0.3, 0.2, 0.4, 0.2, 3, -0.4, 1.0, 0.7])
print(x.shape)
print(regr.predict([x]))

(11,)
[-108.62542255]


In [94]:
np.exp(1)

2.718281828459045

In [95]:
#1
samples = 100

x_data0 = np.random.normal(0, 1, size=[samples,2])  # r == 0  #100개의 빨강데이터
x_data1 = np.random.normal(5, 1, size=[samples,2])  # b == 1  #100개의 파지티브데이터
x_data = np.vstack([x_data0, x_data1])   #vertically stack, 아래로 쌓는것 !=append ㅇ
print(x_data.shape)

# 0을 중심으로 해서 sample 데이터를 100개 만드는데 
# np.random.normal (0<평균>, 1<표준편차>, size=[samples,2]<데이터100개>) 
# (0,0)을 중심으로 만들어짐
# 분산값 크고 작게 조정하면, 그래프 달라짐

(200, 2)


In [96]:
y_data = np.vstack([np.zeros(samples).reshape(samples,1) , np.ones(samples).reshape(samples,1) ])  #y값을 0과 1로만 둠
print(y_data.shape)

(200, 1)


In [97]:
colors = ["red"  if i == 0  else  "blue"  for i  in y_data   ]
# i 루프 도는데 ydata만큼 돌아라:200번
print(colors)
# 앞 100개는 red, 뒤 100은 블루

plt.scatter(x_data[:,0], x_data[:,1], color=colors)

['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'bl

TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable sqrt method

In [98]:
regr.fit(x_data, y_data) # y=w1*x1+w2*x2+b

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [99]:
regr.predict(x_data[0:10]) # 빨강 데이터. 0보다 작으니까

array([[-0.03022672],
       [ 0.16868245],
       [ 0.3402566 ],
       [ 0.09036146],
       [ 0.03846415],
       [-0.15196527],
       [-0.10768559],
       [ 0.21204433],
       [-0.18188421],
       [ 0.05499616]])

In [100]:
regr.predict([[2.7, -2]])  #0보다 크니까 파랑색

array([[0.03013565]])

In [101]:
regr.predict([[2.9, 2.1]])  

array([[0.47504434]])

In [102]:
h= (regr.predict(x_data)[:,0]  >0.5)*1   #[:,0] : 모두 중에서 0번째컬럼
h= (regr.predict(x_data)[:,0]  >0.5) # 만 하면 true false 만 나오니까 비교하기 쉽게 만드려고 *1 해줌

In [103]:
print(h==y_data[:,0])
print(np.sum(h==y_data[:,0])/ y_data.shape[0]) #인식률: 100%

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [104]:
regr.predict([[10, 10]])  #확률은 0-1% 사이라서 1.87은 확률이라 말못함

array([[1.89413199]])

logistic

In [105]:
log_reg=LogisticRegression()
log_reg.fit(x_data,y_data)

C:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [106]:
log_reg.predict([[100,100]])
p=log_reg.predict_proba([[1,1]])
print(p)    
# [[0.98648538 0.01351462]] 앞은 빨강색일 확률, 뒤는 파랑색일확률을 모듈링한것: 확률값이 1일때가 파랑색,
print(p[0][1])
# 값이 1이라는 얘기는 파랑색일 확률 계산

[[0.9887798 0.0112202]]
0.011220199985435513


predict는 목적함수라서 0또는1이나옴
1값이 네거티브일확률/2값이 파지티브일확률


In [107]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib qt5

xx, yy = np.mgrid[-10:10:0.5, -10:10:0.5]
grid = np.c_[xx.flatten(), yy.flatten()]

result = regr.predict(grid)

fig = plt.figure()
ax = plt.axes(projection="3d")


ax.scatter3D(xx.flatten(), yy.flatten(), result, 'r')

In [108]:
log_reg = LogisticRegression()
log_reg.fit(x_data, y_data)

C:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [109]:
xx, yy = np.mgrid[-10:10:0.5, -10:10:0.5]
grid = np.c_[xx.flatten(), yy.flatten()]

result = log_reg.predict_proba(grid)[:,1]

fig = plt.figure()
ax = plt.axes(projection="3d")


ax.scatter3D(xx.flatten(), yy.flatten(), result, 'r')

In [110]:
y = log_reg.coef_[0][0]*100 + log_reg.coef_[0][1] * 100 + log_reg.intercept_
print(y)
print(1/ (1 + np.exp(-y)))

[267.61575124]
[1.]


In [111]:
xx, yy = np.mgrid[-2:8:0.2, -2:8:0.2]
grid = np.c_[xx.flatten(), yy.flatten()]
p = log_reg.predict_proba(grid)
p = p[:,1]


colors = ["red"  if i<  0.5  else  "blue"  for i  in p   ]
plt.scatter(xx.flatten(), yy.flatten(), color = colors, alpha=0.2)

colors = ["red"  if i == 0  else  "blue"  for i  in y_data   ]
plt.scatter(x_data[:,0], x_data[:,1], color=colors)

TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable sqrt method